#!/bin/bash

if [ "$#" -ne 1 ]; then
	echo "usage: $0 [file | url]"
	echo " file - name of a TXT file to print"
	echo " url  - URL to a draft TXT file to print"
fi

TARGET=$1
FNAME=`basename ${TARGET}`

print_rfc () 
{
	enscript -2rG -p - --line-numbers --color=1 -c $1 > ${FNAME}.ps
	ps2pdf ${FNAME}.ps ${FNAME}.pdf
	rm ${FNAME}.ps
}

if [ -f ${TARGET} ]; 
then
	print_rfc "$TARGET"
else
	if [[ $TARGET == http* ]];
	then
        curl -G $TARGET > $FNAME
		print_rfc $FNAME
		rm $FNAME
	else
		# Search for the version
		echo "Target not found..."
	fi
fi

